language: python
python:
  - 3.6.3
install:
  - pip install python-coveralls
  - pip install coverage
  - pip install ecdsa
script:
  - python -m coverage run tests/test_block.py
  - python -m coverage run tests/test_crypto.py
  - python -m coverage run tests/test_ioput.py
  - python -m coverage run tests/test_trans.py
after_success:  
  - coveralls
